services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: |
      python3.11 -m pip install --upgrade pip
      python3.11 -m pip install -r requirements.txt
      python3.11 download_models.py
    startCommand: python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port 10000